# Generated by Django 4.2.4 on 2023-08-21 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_introduction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Introduction',
        ),
    ]
